name: Build

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
  # schedule:
  #   - cron: '0 13 * * 4'

jobs:

  build-on-linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make build
